services:

  mariadb:
    image: mariadb:lts
    container_name: sfcdi_mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: symfony
    ports:
      - 3306:3306
    volumes:
      - sfcdidbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: sfcdi_pma
    restart: always
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 8005:80

  adminer:
    image: adminer
    container_name: sfcdi_adminer
    restart: always
    ports:
      - 8006:8080

  mailer:
    image: schickling/mailcatcher
    container_name: sfcdi_mailcatcher
    ports: ["1025:1025","1080:1080"]

volumes:
  sfcdidbdata: